---
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    working_dir: /app
    deploy:
      replicas: 3  # Specify the number of replicas
    volumes:
      - ./log/log:/app/log

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports:
      - "8080:80"
    depends_on:
      - app
